<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>WinNetSwitch</AssemblyName>
    <RootNamespace>WinNetSwitch.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WinNetSwitch.Core/WinNetSwitch.Core.csproj" />
  </ItemGroup>
</Project>
